### ISSUE TITLE
KeyError: 'epoch'

### ISSUE THREAD

**Issue by KAWAHARA-souta** [KAWAHARA-souta/alma-sbom#11]
```
OpenIPMI-devel:
    version: 2.0.32
    epoch: 0
    release: 3.el9
    arch: i686
    pkgid(sha256?): 79fd84a6b832bc6e2f743c0aa4b0c60e6dac3010d795aea2f4a7ed57737a23a1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721822449.399081 2465355 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
Traceback (most recent call last):
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 704, in <module>
    cli_main()
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 678, in cli_main
    sbom = get_info_about_package(
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 383, in get_info_about_package
    add_package_info(
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 296, in add_package_info
    source_rpm, package_nevra = _get_specific_info_about_package(
  File "/home/khwarizmi/test-sbommaking/alma_sbom.py", line 157, in _get_specific_info_about_package
    epoch=immudb_metadata['epoch'],
KeyError: 'epoch'
```

**Comment by kawaharasouta** [comment]
以下のコミットで修正している
https://github.com/kawaharasouta/alma-sbom/commit/01215ef599a3b0227bf8166130862705ce6fbfcc

※ブランチは https://github.com/kawaharasouta/alma-sbom/tree/fix_incomplete_metadata

**Comment by kawaharasouta** [comment]
hash: 79fd84a6b832bc6e2f743c0aa4b0c60e6dac3010d795aea2f4a7ed57737a23a1
{'Name': 'OpenIPMI-devel-2.0.32-3.el9.i686.rpm', 'Kind': 'file', 'Size': 129828, 'Hash': '79fd84a6b832bc6e2f743c0aa4b0c60e6dac3010d795aea2f4a7ed57737a23a1', 'Metadata': {'arch': 'i686', 'git_commit': '7366558c4f3b4991ab8f68e25f22515e7133a2c0', 'git_ref': 'imports/c9/OpenIPMI-2.0.32-3.el9', 'git_url': 'https://git.almalinux.org/rpms/OpenIPMI.git', 'name': 'OpenIPMI-devel', 'release': '3.el9', 'sbom_api': '0.2', 'source_type': 'git', 'sourcerpm': 'OpenIPMI-2.0.32-3.el9.src.rpm', 'version': '2.0.32'}, 'Signer': 'sbom_signer_almalinux', 'Original_timestamp': '0001-01-01T00:00:00Z', 'timestamp': 1695069478}
