### ISSUE TITLE
cyclonedx-pthon-libのバージョンとdepricatedなAPI (cyclonedx1.6対応

### ISSUE THREAD

**Issue by KAWAHARA-souta** [KAWAHARA-souta/alma-sbom#16]
alma-sbomでは，cyclonedx-python-libのバージョンを2.7.1に固定している．
https://github.com/KAWAHARA-souta/alma-sbom/blob/main/setup.py#L25
なにか理由はある? 
まあ，ライブラリのバージョン上がって壊れるのを未然に防ぐくらいのことだとは思うけれど．

alma-sbomで使っている get_instance() はdepricatedでかつ6.0.0のころに削除されている
https://cyclonedx-python-library.readthedocs.io/en/latest/changelog.html#api-changes-the-details-for-migration
https://github.com/CycloneDX/cyclonedx-python-lib/pull/493

**Comment by KAWAHARA-souta** [comment]
とりあえずここで追加されている．
まあ特別な理由はないとみていいはず．
https://github.com/KAWAHARA-souta/alma-sbom/commit/e86a40780ff2ca9d348190cdf1eb21ca1a75207b#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R26

**Comment by KAWAHARA-souta** [comment]
さきほどあげた，6.0.0の変更のときに，
"Basic support for CycloneDX 1.5"
ってあるから，このころに 1.5 サポートされたっぽい．

**Comment by KAWAHARA-souta** [comment]
これ関係ないけど，cyclonedx1.6 は，7.0.0っぽいかな
https://cyclonedx-python-library.readthedocs.io/en/latest/changelog.html#v7-0-0-2024-04-09

**Comment by KAWAHARA-souta** [comment]
ひとまずターゲットを 'cyclonedx-python-lib==9.0.0' にしようと思ったが，別のライブラリの相性問題が発生
```
ERROR: Cannot install alma-sbom==0.0.2 and cyclonedx-python-lib==9.0.0 because these package versions have conflicting dependencies.                                                        

The conflict is caused by:                     
    alma-sbom 0.0.2 depends on packageurl-python==0.10.3                                      
    cyclonedx-python-lib 9.0.0 depends on packageurl-python<2 and >=0.11
```

ということでもうちょい古いものでまずやってみたい．

cyclonedx-python-lib==8.0.0 でも同じ問題発生

cyclonedx-python-lib==7.0.0 でも同じ問題発生

うーん，cyclondex1.6に対応しているの，7.0.0からなんだよなあ..
先にpackageurl-pythonのバージョン問題から解決するべきか．

**Comment by KAWAHARA-souta** [comment]
とりあえずpackageurl-pythonは0.16.0にupdate 
9d55b0c

**Comment by KAWAHARA-souta** [comment]
目標として9.0.0対応を目指して修正進めている．

最初の問題　
```
  File "/home/khwarizmi/git/alma-sbom/alma_sbom/formats/cyclonedx/component.py", line 2, in <module>                                                                                        
    from cyclonedx.model import HashAlgorithm, HashType, LicenseChoice                        
ImportError: cannot import name 'LicenseChoice' from 'cyclonedx.model' (/home/khwarizmi/git/alma-sbom/env_cdx-updated/lib64/python3.9/site-packages/cyclonedx/model/__init__.py)
```

LicenseChoiceは5.0.0で消えている
https://cyclonedx-python-library.readthedocs.io/en/latest/changelog.html#v5-0-0-2023-10-24
```
Removed class module.LicenseChoice ([#365](https://github.com/CycloneDX/cyclonedx-python-lib/issues/365) via [#466](https://github.com/CycloneDX/cyclonedx-python-lib/pull/466))
Use dedicated classes module.license.DisjunctliveLicense and module.license.LicenseExpression instead
```

とりあえずexample (https://cyclonedx-python-library.readthedocs.io/en/latest/examples.html) を参考にして，LicenseFactoryを利用して書いてみている．
※コミットはあとで記録しようかな

**Comment by KAWAHARA-souta** [comment]
次の問題
```
  File "/home/khwarizmi/git/alma-sbom/alma_sbom/formats/cyclonedx/document.py", line 69, in __init__                                                                                                   
    self.bom.metadata.tools.add(Tool(            
AttributeError: 'ToolRepository' object has no attribute 'add' 
```

正確な根拠ではないのだが，v8.0.0においてtool関連がかなり修正されていて
https://cyclonedx-python-library.readthedocs.io/en/latest/changelog.html#v8-0-0-2024-10-14
たぶんだけど`bom.metadata.tools.components.add()` なのかな? (componentsが入った)

ここtoolの修正が多くまとめて入っているのであとで注意してみたほうがいいかも

**Comment by KAWAHARA-souta** [comment]
次の問題
```
  File "/home/khwarizmi/git/alma-sbom/alma_sbom/formats/cyclonedx/component.py", line 45, in _make_hash                                                                
    return HashType(                     
TypeError: __init__() got an unexpected keyword argument 'algorithm'
```

HashTypeのコンストラクタのエラーなんだが，
これソース見てみるとインスタンスを生成するfrom_*()系のコンストラクタがいくつかあるので，それを使うべきだなと思うなどする．

再度よくよく見ていて気づいたこと..
type.py内にalma-sbom用にHashクラスを作って，かつAlgorithmクラスも作っていて，その値はcyclonedx-python-lib内のHashAlgorithmとフレンドリーになるように作っていた(作るしかなかった)のだが，↑に書いたようにfrom_*()系のコンストラクタがあって，from_hashlib_alg()というのがhashlibで使うようなstrから生成するコンストラクタらしいので，それを使う形に変更した方がいいな．

とりあえず現時点では今のままの形を保って実装しなおした．
HashTypeのメンバーの名前が変わってるっぽく，algorithmからalg，valueからcontentに変えた.

**Comment by KAWAHARA-souta** [comment]
次の問題
```
  File "/home/khwarizmi/git/alma-sbom/alma_sbom/formats/cyclonedx/component.py", line 17, in component_from_package
    return Component(                                                                                               
TypeError: __init__() got an unexpected keyword argument 'component_type'
```

content_typeからtypeに変わったかな

**Comment by KAWAHARA-souta** [comment]
次の問題
```
  File "/home/khwarizmi/git/alma-sbom/alma_sbom/formats/cyclonedx/document.py", line 53, in _write_xml                                                                 
    output_str = formatter.output_as_string()
 (...)
  File "/home/khwarizmi/git/alma-sbom/env_cdx-updated/lib64/python3.9/site-packages/cyclonedx/model/tool.py", line 176, in from_component
    vendor=component.group,                                                                                                                                         
AttributeError: 'Tool' object has no attribute 'group'
```

これは根が深そう

```
173     @classmethod
174     def from_component(cls: Type['Tool'], component: 'Component') -> 'Tool':
175         print('hello from Tool.from_component()')
176         print(f'type(component): {type(component)}')
177         return cls(                                                              
178             vendor=component.group,                                              
179             name=component.name,                                                 
180             version=component.version,                                           
181             hashes=component.hashes,                                             
182             external_references=component.external_references,                   
183         ) 
=====
hello from Tool.from_component()                                                     
type(component): <class 'cyclonedx.model.tool.Tool'>                                 
Traceback (most recent call last): 
```
上のcomponent.groupというところでエラーになっていて，型ヒントだとComponentクラスのインスタンスだということになっているんだが，これがToolクラスになっているらしくエラーに落ちる．
まだライブラリの問題かは正確に分からないのでより深い調査必要．調査中．


追記
次のように値はバッチリ記憶にある内容となっていて，これは多分メンバーメソッドのバージョン間での揺れがつもりつもって顕在化したパターンだと思うので対処したい．
```
hello from Tool.from_component()          
type(component): <class 'cyclonedx.model.tool.Tool'>                                
<Tool name=AlmaLinux Build System, version=0.1, vendor=AlmaLinux OS Foundation>
```

さらに，とりあえずツール情報をaddしてるところを全部動かなくしてみたらなにやらゴミが吐き出されることは確認できた．
やっぱりツールの追加の仕方は問題ね．
それから，吐き出されたゴミは明らかにデータが足りないので，やっぱり色々データの配置場所とか変わってるのだと思う．

**Comment by KAWAHARA-souta** [comment]
その後の調査過程ここにメモしておくの忘れた．

とりあえず，
- ライブラリのアップデート
- 1.6対応(抽象化factory関数みたいなの使って再実装)
- (1.6対応とほとんどかぶるけど) writerの実装をライブラリベースのものにアップデート
という感じで進めた．

**Comment by KAWAHARA-souta** [comment]
その後，exampleにあるようなvalidationでも実装してみようかしらと思ったのだが，

```
cyclonedx.exception.MissingOptionalDependencyException: This functionality requires optional dependencies.                                                                             
Please install `cyclonedx-python-lib` with the extra "json-validation".
```

ということで，validationにはエクストラなインストール方法をしないといけないらしい．
とりあえずこの対応は別のMRに分けて実装した方がよさそうじゃないかな?
